// <auto-generated />
namespace WebsiteBanTraiCay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateloginusergoogle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateloginusergoogle));
        
        string IMigrationMetadata.Id
        {
            get { return "202212241642137_update login user google"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
