// <auto-generated />
namespace WebsiteBanTraiCay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateanalyticwebmastertoolgooglemap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateanalyticwebmastertoolgooglemap));
        
        string IMigrationMetadata.Id
        {
            get { return "202212240154373_update analytic webmastertool googlemap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
